### ISSUE TITLE
Admin edit event appears to offer no way to alter "description", only "short description"

### ISSUE THREAD

**Issue by WakeRealityDev** [aldryn/aldryn-events#250]
From this URL: admin/aldryn_events/event/

I can edit an event, but there seems to be no apparent way to revise the "description", only the "short description:".

**Comment by WakeRealityDev** [comment]
I'm still stuck on this. As "short description" is truncated at 25 words on the detail view due to the front end instructing it to truncate ( code: https://github.com/aldryn/aldryn-events/blob/master/aldryn_events/boilerplates/bootstrap3/templates/aldryn_events/includes/event.html#L67 ).

The solutions seems to be to use the "description" field, which works for longer length, but offers no way to edit from the admin/aldryn_events/event/ page?

**Comment by czpython** [comment]
Description is edited through the frontend using plugins.
